# Init ZSH plugins
#
autoload -Uz compinit vcs_info add-zsh-hook
fpath=(~/.zsh $fpath)

# beeping is annoying
unsetopt BEEP

# Enable vi mode
bindkey -v

REPORTTIME=3
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000

setopt NO_CASE_GLOB
setopt GLOB_COMPLETE
setopt AUTO_CD
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt PROMPT_SUBST
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE

#
# Exports
#
export CLICOLOR=1
export LC_MESSAGES=C
export LSCOLORS="gxfxcxdxbxegedabagacad"
export TERM=xterm-256color

#
# ZSH Completion
#
zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'
zstyle :compinstall filename '/Users/nemanja.vasic.ext/.zshrc'
compinit

#
# GIT integration
#
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' unstagedstr '*'
zstyle ':vcs_info:git:*' stagedstr '+'
zstyle ':vcs_info:git:*' formats " (%F{003}%b%u%c%f)"
zstyle ':vcs_info:git:*' actionformats "(%F{003}%b (%a)%u%c%f)"
add-zsh-hook precmd vcs_info

#
# Aliases
#
alias ..="cd .."
alias ...="cd ../.."
alias la="ls -lAh"
alias gco="git checkout"
alias zshconfig="vim ~/.zshrc"
alias used_ports="lsof -i -P -n | grep LISTEN"
alias docker_wipe="docker system prune"
alias docker_wipe_all="docker system prune --all --volumes"

#
# Prompt
#
PROMPT='$ %F{144}%2~%f${vcs_info_msg_0_} '

function brew_update {
  [ -n "$(command -v brew_update_preflight)" ] && brew_update_preflight
  [ -x "$(command -v brew)" ] && brew update && brew upgrade && brew cleanup --prune all -s && brew doctor && brew missing;
}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# install zsh with brew or via GitHub script
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export MOB_WIP_BRANCH_PREFIX="mob-"
